name: Create Hotfix Branch

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Target version for hotfix (e.g., v0.1.0)'
        required: true
        type: string
        default: 'v0.1.0'
      hotfix-suffix:
        description: 'Hotfix suffix (e.g., hotfix.1)'
        required: true
        default: 'hotfix.1'
        type: string

jobs:
  create-hotfix-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      pull-requests: write
    
    outputs:
      hotfix-branch: ${{ steps.create-hotfix.outputs.hotfix-branch }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup test environment
        run: |
          echo "🛠️ Setting up test environment..."
          git config user.name "Test Bot"
          git config user.email "test@example.com"
          
      - name: Display current repository state
        run: |
          echo "📋 Current repository state:"
          echo "Branches:"
          git branch -a
          echo ""
          echo "Tags:"
          git tag --list
          echo ""
          echo "Target version: ${{ github.event.inputs.version }}"
          echo "Hotfix suffix: ${{ github.event.inputs.hotfix-suffix }}"
          
      - name: Verify target version exists
        run: |
          if ! git tag --list | grep -q "^${{ github.event.inputs.version }}$"; then
            echo "❌ Error: Tag '${{ github.event.inputs.version }}' does not exist"
            echo "Available tags:"
            git tag --list
            exit 1
          fi
          echo "✅ Target version '${{ github.event.inputs.version }}' found"
          
      - name: Create Hotfix Branch
        id: create-hotfix
        uses: egoavara/propagate-merger@v0.0.1
        with:
          mode: branch-create
          version: ${{ github.event.inputs.version }}
          hotfix-suffix: ${{ github.event.inputs.hotfix-suffix }}
          github-token: ${{ github.token }}
          
      - name: Display results
        run: |
          echo "🎉 Hotfix branch created successfully!"
          echo "Branch name: ${{ steps.create-hotfix.outputs.hotfix-branch }}"
          echo ""
          echo "📊 Final repository state:"
          echo "Branches:"
          git branch -a
          echo ""
          echo "Recent commits on hotfix branch:"
          git checkout ${{ steps.create-hotfix.outputs.hotfix-branch }}
          git log --oneline -n 5
          
      - name: Next steps
        run: |
          echo "🚀 Next steps:"
          echo "1. Make your hotfix changes on branch: ${{ steps.create-hotfix.outputs.hotfix-branch }}"
          echo "2. Commit your changes"
          echo "3. Run the 'Auto Merge Hotfix' workflow with the same parameters"