name: Test GitHub API Access

on:
  workflow_dispatch:

permissions: write-all

jobs:
  test-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test GitHub API with different tokens
        run: |
          echo "🔍 Testing GitHub API access..."
          
          # Test with default token
          echo "Testing with GITHUB_TOKEN:"
          curl -H "Authorization: token ${{ github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/git/refs/heads || echo "Failed with GITHUB_TOKEN"
          
          echo ""
          echo "Testing with GH_PAT:"
          if [ -n "${{ secrets.GH_PAT }}" ]; then
            curl -H "Authorization: token ${{ secrets.GH_PAT }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 https://api.github.com/repos/${{ github.repository }}/git/refs/heads || echo "Failed with GH_PAT"
          else
            echo "GH_PAT not available"
          fi
          
      - name: Try to create a test branch with API
        run: |
          echo "🌿 Testing branch creation via API..."
          
          # Get main branch SHA
          MAIN_SHA=$(curl -H "Authorization: token ${{ secrets.GH_PAT || github.token }}" \
                          -H "Accept: application/vnd.github.v3+json" \
                          https://api.github.com/repos/${{ github.repository }}/git/refs/heads/main | jq -r '.object.sha')
          
          echo "Main SHA: $MAIN_SHA"
          
          # Try to create test branch
          curl -X POST \
               -H "Authorization: token ${{ secrets.GH_PAT || github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/git/refs \
               -d '{
                 "ref": "refs/heads/test-api-branch",
                 "sha": "'$MAIN_SHA'"
               }' || echo "Failed to create test branch"
               
      - name: Check if test branch was created
        run: |
          echo "🔍 Checking if test branch exists..."
          curl -H "Authorization: token ${{ secrets.GH_PAT || github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/git/refs/heads/test-api-branch || echo "Test branch not found"
               
      - name: Clean up test branch
        run: |
          echo "🧹 Cleaning up test branch..."
          curl -X DELETE \
               -H "Authorization: token ${{ secrets.GH_PAT || github.token }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/git/refs/heads/test-api-branch || echo "Failed to delete test branch"